### ISSUE TITLE
TOKEN Assignment?

### ISSUE THREAD

**Issue by whoastonic** [alex-taxiera/eris-boiler#95]
First things first, where is the assignment?

https://github.com/alex-taxiera/eris-boiler/blob/5e3ba255948e7c79e9d5b558e345205c27bae9ca/lib/data-client/index.js#L28

**Comment by alex-taxiera** [comment]
it's a constructor parameter
https://github.com/alex-taxiera/eris-boiler/blob/5e3ba255948e7c79e9d5b558e345205c27bae9ca/lib/data-client/index.js#L21
